logging:
  level:
    com.palmble.dal: DEBUG
server:
  port: 8383
spring: 
  resources: 
    staticLocations: classpath:/META-INF/resources/,classpath:/resources/, classpath:/static/, file:${image.location}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    #password: root
    password: a/xOejRkf3Ge
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://127.0.0.1:3306/base_project?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    url: jdbc:mysql://180.76.98.239:3306/base_project?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
      
    #连接池的配置信息  
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    maxWait: 60000  
    timeBetweenEvictionRunsMillis: 60000  
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROM DUAL  
    testWhileIdle: true  
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true  
    maxPoolPreparedStatementPerConnectionSize: 20  
    filters: stat,wall,logback
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
mybatis:
  #实体类所做包
  type-aliases-package: com.palmble.entity
  #mapper.xml所在位置
  mapper-locations: classpath:/mapper/*.xml
